# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-27 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginreg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('schedule', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('userss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_traveling', to='loginreg.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserTravel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_travel', to='travelbuddy.Travel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_users', to='loginreg.User')),
            ],
        ),
    ]
